# Generated by Django 3.0.7 on 2020-08-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200728_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='published_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
